import React from 'react';
import { notFound, permanentRedirect } from 'next/navigation';
import { findCityByRootSlug, getCityRootSlug } from '@/lib/geo/city-lookup';
import { getAllCities } from '@/lib/geo/cities';
import { CityPageClient } from '@/components/common/CityPageClient';
import { FaqAccordion } from '@/components/common/FaqAccordion';
import { RelatedLinksHub } from '@/components/common/RelatedLinksHub';
import { Breadcrumbs } from '@/components/common/Breadcrumbs';
import { Metadata } from 'next';
import { buildPageMetadata } from '@/lib/seo/metadata';
import { JsonLd } from '@/components/seo/JsonLd';
import { getCityFaqs, getCityTemporalData } from '@/lib/seo/page-faqs';
import { CITY_CUSTOM_CONTENT } from '@/lib/seo/city-custom-content';
import { EditorialContentBlock } from '@/components/common/EditorialContentBlock';

interface Props {
  params: Promise<{ city: string }>;
}

export async function generateStaticParams() {
  return getAllCities().map((c) => ({ city: getCityRootSlug(c) }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { city: rawSlug } = await params;
  const city = findCityByRootSlug(rawSlug);
  if (!city) return buildPageMetadata('City Not Found', 'City not found.', `/time/${rawSlug}`);

  const cleanSlug = getCityRootSlug(city);
  const custom = CITY_CUSTOM_CONTENT[cleanSlug];
  if (custom) {
    return buildPageMetadata(custom.title, custom.description, `/time/${cleanSlug}`);
  }

  const data = getCityTemporalData(city);
  const dstText = data.observesDST
    ? (data.isDstCurrentlyActive ? `${data.timezoneAbbr} daylight time active` : `${data.timezoneAbbr} standard time`)
    : `permanent ${data.baseOffset} with zero DST clock shifts`;

  return buildPageMetadata(
    `What Time is it in ${city.name}? Exact Local Time Now`,
    `Current local time in ${city.name}, ${city.country} right now: atomic clock with seconds, ${data.timezoneAbbr} (${data.baseOffset}), ${dstText}, today's sunrise & sunset, and time converter.`,
    `/time/${cleanSlug}`
  );
}

export default async function CanonicalCityTimePage({ params }: Props) {
  const { city: rawSlug } = await params;
  const city = findCityByRootSlug(rawSlug);

  if (!city) {
    notFound();
  }

  const cleanSlug = getCityRootSlug(city);
  if (rawSlug !== cleanSlug) {
    permanentRedirect(`/time/${cleanSlug}`);
  }

  const custom = CITY_CUSTOM_CONTENT[cleanSlug];
  const temporalData = getCityTemporalData(city);
  const cityFaqs = custom?.faqs || getCityFaqs(temporalData);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Semantic Breadcrumbs & Schema.org JSON-LD (auto-generated by Breadcrumbs) */}
      <Breadcrumbs
        items={[
          { name: 'Cities', url: '/cities' },
          { name: `${city.name}, ${city.country}`, url: `/time/${cleanSlug}` },
        ]}
      />
      <JsonLd type="faq" data={cityFaqs} />

      <CityPageClient city={city} h1Title={custom?.h1} />

      {custom && (
        <EditorialContentBlock content={custom} badgeLabel="Verified Atomic Local Time" />
      )}

      <div className="pt-4 border-t border-slate-200 dark:border-slate-800">
        <FaqAccordion items={cityFaqs} />
      </div>

      <RelatedLinksHub title={`Explore More Locations Near ${city.name}`} />
    </div>
  );
}
