export type CityData = City;

export interface City {
  id: string;
  name: string;
  slug: string;
  country: string;
  countryCode: string;
  region?: string;
  lat: number;
  lng: number;
  timezone: string;
  population?: string;
  landmarkId?: "eiffel" | "liberty" | "bigben" | "tokyotower" | "burj" | "indiagate" | "operahouse" | "generic";
  isCapital?: boolean;
  featured?: boolean;
  aliases: string[];
}

export const CITIES: City[] = [
  {
    id: "paris-fr",
    name: "Paris",
    slug: "paris-france",
    country: "France",
    countryCode: "FR",
    region: "Île-de-France",
    lat: 48.8566,
    lng: 2.3522,
    timezone: "Europe/Paris",
    population: "2.1 million",
    landmarkId: "eiffel",
    isCapital: true,
    featured: true,
    aliases: ["Paris", "France", "CET", "CEST", "Eiffel"]
  },
  {
    id: "new-york-us",
    name: "New York",
    slug: "new-york-united-states",
    country: "United States",
    countryCode: "US",
    region: "New York",
    lat: 40.7128,
    lng: -74.0060,
    timezone: "America/New_York",
    population: "8.3 million",
    landmarkId: "liberty",
    isCapital: false,
    featured: true,
    aliases: ["NYC", "New York City", "Manhattan", "EST", "EDT", "Eastern Time"]
  },
  {
    id: "london-gb",
    name: "London",
    slug: "london-united-kingdom",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Greater London",
    lat: 51.5074,
    lng: -0.1278,
    timezone: "Europe/London",
    population: "8.9 million",
    landmarkId: "bigben",
    isCapital: true,
    featured: true,
    aliases: ["London", "UK", "Britain", "GMT", "BST", "Greenwich", "Big Ben"]
  },
  {
    id: "tokyo-jp",
    name: "Tokyo",
    slug: "tokyo-japan",
    country: "Japan",
    countryCode: "JP",
    region: "Kanto",
    lat: 35.6762,
    lng: 139.6503,
    timezone: "Asia/Tokyo",
    population: "14.0 million",
    landmarkId: "tokyotower",
    isCapital: true,
    featured: true,
    aliases: ["Tokyo", "Japan", "JST", "Tokyo Tower", "Edo"]
  },
  {
    id: "dubai-ae",
    name: "Dubai",
    slug: "dubai-united-arab-emirates",
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Dubai Emirate",
    lat: 25.2048,
    lng: 55.2708,
    timezone: "Asia/Dubai",
    population: "3.6 million",
    landmarkId: "burj",
    isCapital: false,
    featured: true,
    aliases: ["Dubai", "UAE", "Emirates", "GST", "Burj Al Arab", "Burj Khalifa"]
  },
  {
    id: "delhi-in",
    name: "Delhi",
    slug: "delhi-india",
    country: "India",
    countryCode: "IN",
    region: "Delhi NCR",
    lat: 28.6139,
    lng: 77.2090,
    timezone: "Asia/Kolkata",
    population: "33.0 million",
    landmarkId: "indiagate",
    isCapital: true,
    featured: true,
    aliases: ["Delhi", "New Delhi", "India", "IST", "India Gate", "Bharat", "UTC+5:30"]
  },
  {
    id: "sydney-au",
    name: "Sydney",
    slug: "sydney-australia",
    country: "Australia",
    countryCode: "AU",
    region: "New South Wales",
    lat: -33.8688,
    lng: 151.2093,
    timezone: "Australia/Sydney",
    population: "5.3 million",
    landmarkId: "operahouse",
    isCapital: false,
    featured: true,
    aliases: ["Sydney", "Australia", "AEST", "AEDT", "Sydney Opera House", "Harbour"]
  },
  {
    id: "los-angeles-us",
    name: "Los Angeles",
    slug: "los-angeles-united-states",
    country: "United States",
    countryCode: "US",
    region: "California",
    lat: 34.0522,
    lng: -118.2437,
    timezone: "America/Los_Angeles",
    population: "3.8 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["LA", "Los Angeles", "California", "PST", "PDT", "Pacific Time"]
  },
  {
    id: "chicago-us",
    name: "Chicago",
    slug: "chicago-united-states",
    country: "United States",
    countryCode: "US",
    region: "Illinois",
    lat: 41.8781,
    lng: -87.6298,
    timezone: "America/Chicago",
    population: "2.6 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Chicago", "CST", "CDT", "Central Time"]
  },
  {
    id: "san-francisco-us",
    name: "San Francisco",
    slug: "san-francisco-united-states",
    country: "United States",
    countryCode: "US",
    region: "California",
    lat: 37.7749,
    lng: -122.4194,
    timezone: "America/Los_Angeles",
    population: "808,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["SF", "Bay Area", "Silicon Valley", "PST", "PDT"]
  },
  {
    id: "toronto-ca",
    name: "Toronto",
    slug: "toronto-canada",
    country: "Canada",
    countryCode: "CA",
    region: "Ontario",
    lat: 43.6532,
    lng: -79.3832,
    timezone: "America/Toronto",
    population: "2.9 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Toronto", "Ontario", "Canada", "EST", "EDT"]
  },
  {
    id: "singapore-sg",
    name: "Singapore",
    slug: "singapore",
    country: "Singapore",
    countryCode: "SG",
    region: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    timezone: "Asia/Singapore",
    population: "5.9 million",
    landmarkId: "generic",
    isCapital: true,
    featured: false,
    aliases: ["Singapore", "SG", "SGT", "Lion City"]
  },
  {
    id: "hong-kong-hk",
    name: "Hong Kong",
    slug: "hong-kong",
    country: "China",
    countryCode: "HK",
    region: "Hong Kong SAR",
    lat: 22.3193,
    lng: 114.1694,
    timezone: "Asia/Hong_Kong",
    population: "7.4 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Hong Kong", "HK", "HKT"]
  },
  {
    id: "berlin-de",
    name: "Berlin",
    slug: "berlin-germany",
    country: "Germany",
    countryCode: "DE",
    region: "Berlin",
    lat: 52.5200,
    lng: 13.4050,
    timezone: "Europe/Berlin",
    population: "3.8 million",
    landmarkId: "generic",
    isCapital: true,
    featured: false,
    aliases: ["Berlin", "Germany", "Deutschland", "CET", "CEST"]
  },
  {
    id: "mumbai-in",
    name: "Mumbai",
    slug: "mumbai-india",
    country: "India",
    countryCode: "IN",
    region: "Maharashtra",
    lat: 19.0760,
    lng: 72.8777,
    timezone: "Asia/Kolkata",
    population: "21.3 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Mumbai", "Bombay", "Maharashtra", "IST"]
  },
  {
    id: "bengaluru-in",
    name: "Bengaluru",
    slug: "bengaluru-india",
    country: "India",
    countryCode: "IN",
    region: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    timezone: "Asia/Kolkata",
    population: "13.6 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Bangalore", "Bengaluru", "Karnataka", "IST"]
  },
  {
    id: "cairo-eg",
    name: "Cairo",
    slug: "cairo-egypt",
    country: "Egypt",
    countryCode: "EG",
    region: "Cairo Governorate",
    lat: 30.0444,
    lng: 31.2357,
    timezone: "Africa/Cairo",
    population: "10.0 million",
    landmarkId: "generic",
    isCapital: true,
    featured: false,
    aliases: ["Cairo", "Egypt", "EET", "EEST"]
  },
  {
    id: "rome-it",
    name: "Rome",
    slug: "rome-italy",
    country: "Italy",
    countryCode: "IT",
    region: "Lazio",
    lat: 41.9028,
    lng: 12.4964,
    timezone: "Europe/Rome",
    population: "2.8 million",
    landmarkId: "generic",
    isCapital: true,
    featured: false,
    aliases: ["Rome", "Roma", "Italy", "Italia", "CET", "CEST"]
  },
  {
    id: "madrid-es",
    name: "Madrid",
    slug: "madrid-spain",
    country: "Spain",
    countryCode: "ES",
    region: "Community of Madrid",
    lat: 40.4168,
    lng: -3.7038,
    timezone: "Europe/Madrid",
    population: "3.3 million",
    landmarkId: "generic",
    isCapital: true,
    featured: false,
    aliases: ["Madrid", "Spain", "España", "CET", "CEST"]
  },
  {
    id: "seoul-kr",
    name: "Seoul",
    slug: "seoul-south-korea",
    country: "South Korea",
    countryCode: "KR",
    region: "Seoul Capital Area",
    lat: 37.5665,
    lng: 126.9780,
    timezone: "Asia/Seoul",
    population: "9.7 million",
    landmarkId: "generic",
    isCapital: true,
    featured: false,
    aliases: ["Seoul", "Korea", "KST"]
  },
  {
    id: "sao-paulo-br",
    name: "São Paulo",
    slug: "sao-paulo-brazil",
    country: "Brazil",
    countryCode: "BR",
    region: "São Paulo",
    lat: -23.5505,
    lng: -46.6333,
    timezone: "America/Sao_Paulo",
    population: "12.3 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Sao Paulo", "São Paulo", "Brazil", "BRT"]
  },
  {
    id: "zurich-ch",
    name: "Zurich",
    slug: "zurich-switzerland",
    country: "Switzerland",
    countryCode: "CH",
    region: "Canton of Zurich",
    lat: 47.3769,
    lng: 8.5417,
    timezone: "Europe/Zurich",
    population: "420,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Zurich", "Zürich", "Switzerland", "CET", "CEST"]
  },
  {
    id: "houston-us",
    name: "Houston",
    slug: "houston-united-states",
    country: "United States",
    countryCode: "US",
    region: "Texas",
    lat: 29.7604,
    lng: -95.3698,
    timezone: "America/Chicago",
    population: "2.3 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Houston", "Space City", "TX", "Central Time", "CST", "CDT"]
  },
  {
    id: "phoenix-us",
    name: "Phoenix",
    slug: "phoenix-united-states",
    country: "United States",
    countryCode: "US",
    region: "Arizona",
    lat: 33.4484,
    lng: -112.0740,
    timezone: "America/Phoenix",
    population: "1.6 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Phoenix", "PHX", "AZ", "Valley of the Sun", "MST", "Mountain Standard Time"]
  },
  {
    id: "dallas-us",
    name: "Dallas",
    slug: "dallas-united-states",
    country: "United States",
    countryCode: "US",
    region: "Texas",
    lat: 32.7767,
    lng: -96.7970,
    timezone: "America/Chicago",
    population: "1.3 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Dallas", "DFW", "TX", "Big D", "CST", "CDT"]
  },
  {
    id: "austin-us",
    name: "Austin",
    slug: "austin-united-states",
    country: "United States",
    countryCode: "US",
    region: "Texas",
    lat: 30.2672,
    lng: -97.7431,
    timezone: "America/Chicago",
    population: "975,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Austin", "TX", "ATX", "CST", "CDT"]
  },
  {
    id: "san-diego-us",
    name: "San Diego",
    slug: "san-diego-united-states",
    country: "United States",
    countryCode: "US",
    region: "California",
    lat: 32.7157,
    lng: -117.1611,
    timezone: "America/Los_Angeles",
    population: "1.4 million",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["San Diego", "CA", "PST", "PDT", "Pacific Time"]
  },
  {
    id: "seattle-us",
    name: "Seattle",
    slug: "seattle-united-states",
    country: "United States",
    countryCode: "US",
    region: "Washington",
    lat: 47.6062,
    lng: -122.3321,
    timezone: "America/Los_Angeles",
    population: "750,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Seattle", "WA", "Emerald City", "PST", "PDT"]
  },
  {
    id: "denver-us",
    name: "Denver",
    slug: "denver-united-states",
    country: "United States",
    countryCode: "US",
    region: "Colorado",
    lat: 39.7392,
    lng: -104.9903,
    timezone: "America/Denver",
    population: "715,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Denver", "CO", "Mile High City", "MST", "MDT", "Mountain Time"]
  },
  {
    id: "boston-us",
    name: "Boston",
    slug: "boston-united-states",
    country: "United States",
    countryCode: "US",
    region: "Massachusetts",
    lat: 42.3601,
    lng: -71.0589,
    timezone: "America/New_York",
    population: "675,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Boston", "MA", "Beantown", "EST", "EDT", "Eastern Time"]
  },
  {
    id: "las-vegas-us",
    name: "Las Vegas",
    slug: "las-vegas-united-states",
    country: "United States",
    countryCode: "US",
    region: "Nevada",
    lat: 36.1699,
    lng: -115.1398,
    timezone: "America/Los_Angeles",
    population: "650,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Las Vegas", "Vegas", "NV", "PST", "PDT"]
  },
  {
    id: "el-paso-us",
    name: "El Paso",
    slug: "el-paso-united-states",
    country: "United States",
    countryCode: "US",
    region: "Texas",
    lat: 31.7619,
    lng: -106.4850,
    timezone: "America/Denver",
    population: "680,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["El Paso", "TX", "Sun City", "MST", "MDT"]
  },
  {
    id: "albuquerque-us",
    name: "Albuquerque",
    slug: "albuquerque-united-states",
    country: "United States",
    countryCode: "US",
    region: "New Mexico",
    lat: 35.0844,
    lng: -106.6504,
    timezone: "America/Denver",
    population: "560,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Albuquerque", "ABQ", "NM", "MST", "MDT"]
  },
  {
    id: "tucson-us",
    name: "Tucson",
    slug: "tucson-united-states",
    country: "United States",
    countryCode: "US",
    region: "Arizona",
    lat: 32.2226,
    lng: -110.9747,
    timezone: "America/Phoenix",
    population: "545,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Tucson", "AZ", "Old Pueblo", "MST"]
  },
  {
    id: "mesa-us",
    name: "Mesa",
    slug: "mesa-united-states",
    country: "United States",
    countryCode: "US",
    region: "Arizona",
    lat: 33.4152,
    lng: -111.8315,
    timezone: "America/Phoenix",
    population: "505,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Mesa", "AZ", "MST"]
  },
  {
    id: "atlanta-us",
    name: "Atlanta",
    slug: "atlanta-united-states",
    country: "United States",
    countryCode: "US",
    region: "Georgia",
    lat: 33.7490,
    lng: -84.3880,
    timezone: "America/New_York",
    population: "500,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Atlanta", "ATL", "GA", "EST", "EDT"]
  },
  {
    id: "miami-us",
    name: "Miami",
    slug: "miami-united-states",
    country: "United States",
    countryCode: "US",
    region: "Florida",
    lat: 25.7617,
    lng: -80.1918,
    timezone: "America/New_York",
    population: "440,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Miami", "FL", "Magic City", "EST", "EDT"]
  },
  {
    id: "minneapolis-us",
    name: "Minneapolis",
    slug: "minneapolis-united-states",
    country: "United States",
    countryCode: "US",
    region: "Minnesota",
    lat: 44.9778,
    lng: -93.2650,
    timezone: "America/Chicago",
    population: "425,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Minneapolis", "MN", "Twin Cities", "CST", "CDT"]
  },
  {
    id: "honolulu-us",
    name: "Honolulu",
    slug: "honolulu-united-states",
    country: "United States",
    countryCode: "US",
    region: "Hawaii",
    lat: 21.3069,
    lng: -157.8583,
    timezone: "Pacific/Honolulu",
    population: "350,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Honolulu", "Oahu", "HI", "Hawaii Standard Time", "HST"]
  },
  {
    id: "anchorage-us",
    name: "Anchorage",
    slug: "anchorage-united-states",
    country: "United States",
    countryCode: "US",
    region: "Alaska",
    lat: 61.2181,
    lng: -149.9003,
    timezone: "America/Anchorage",
    population: "290,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Anchorage", "AK", "Alaska Time", "AKST", "AKDT"]
  },
  {
    id: "scottsdale-us",
    name: "Scottsdale",
    slug: "scottsdale-united-states",
    country: "United States",
    countryCode: "US",
    region: "Arizona",
    lat: 33.4942,
    lng: -111.9261,
    timezone: "America/Phoenix",
    population: "240,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Scottsdale", "AZ", "MST"]
  },
  {
    id: "boise-us",
    name: "Boise",
    slug: "boise-united-states",
    country: "United States",
    countryCode: "US",
    region: "Idaho",
    lat: 43.6150,
    lng: -116.2023,
    timezone: "America/Boise",
    population: "235,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Boise", "ID", "City of Trees", "MST", "MDT"]
  },
  {
    id: "salt-lake-city-us",
    name: "Salt Lake City",
    slug: "salt-lake-city-united-states",
    country: "United States",
    countryCode: "US",
    region: "Utah",
    lat: 40.7608,
    lng: -111.8910,
    timezone: "America/Denver",
    population: "200,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Salt Lake City", "SLC", "UT", "MST", "MDT"]
  },
  {
    id: "flagstaff-us",
    name: "Flagstaff",
    slug: "flagstaff-united-states",
    country: "United States",
    countryCode: "US",
    region: "Arizona",
    lat: 35.1983,
    lng: -111.6513,
    timezone: "America/Phoenix",
    population: "76,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Flagstaff", "AZ", "MST"]
  },
  {
    id: "hilo-us",
    name: "Hilo",
    slug: "hilo-united-states",
    country: "United States",
    countryCode: "US",
    region: "Hawaii",
    lat: 19.7297,
    lng: -155.0900,
    timezone: "Pacific/Honolulu",
    population: "44,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Hilo", "HI", "Big Island", "HST"]
  },
  {
    id: "fairbanks-us",
    name: "Fairbanks",
    slug: "fairbanks-united-states",
    country: "United States",
    countryCode: "US",
    region: "Alaska",
    lat: 64.8378,
    lng: -147.7164,
    timezone: "America/Anchorage",
    population: "32,500",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Fairbanks", "AK", "Golden Heart City", "AKST", "AKDT"]
  },
  {
    id: "juneau-us",
    name: "Juneau",
    slug: "juneau-united-states",
    country: "United States",
    countryCode: "US",
    region: "Alaska",
    lat: 58.3019,
    lng: -134.4197,
    timezone: "America/Juneau",
    population: "32,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Juneau", "AK", "Alaska Capital", "AKST", "AKDT"]
  },
  {
    id: "kahului-us",
    name: "Kahului",
    slug: "kahului-united-states",
    country: "United States",
    countryCode: "US",
    region: "Hawaii",
    lat: 20.8893,
    lng: -156.4729,
    timezone: "Pacific/Honolulu",
    population: "28,000",
    landmarkId: "generic",
    isCapital: false,
    featured: false,
    aliases: ["Kahului", "Maui", "HI", "HST"]
  },
  {
    id: "washington-dc-us",
    name: "Washington D.C.",
    slug: "washington-dc-united-states",
    country: "United States",
    countryCode: "US",
    region: "District of Columbia",
    lat: 38.9072,
    lng: -77.0369,
    timezone: "America/New_York",
    population: "710,000",
    landmarkId: "generic",
    isCapital: true,
    featured: true,
    aliases: ["Washington", "DC", "Washington DC", "District of Columbia", "EST", "EDT"]
  }
];

export function getAllCities(): City[] {
  return CITIES;
}

export function getFeaturedCities(): City[] {
  return CITIES.filter(c => c.featured);
}

export function getCityBySlug(slug: string): City | undefined {
  if (!slug) return undefined;
  const normalized = slug.toLowerCase().trim();
  const direct = CITIES.find(c => c.slug === normalized || c.id === normalized);
  if (direct) return direct;
  const byName = CITIES.find(c => {
    const nameSlug = c.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    return nameSlug === normalized;
  });
  if (byName) return byName;
  const byPrefix = CITIES.find(c => c.id.replace(/-[a-z]{2}$/, '') === normalized);
  if (byPrefix) return byPrefix;
  return CITIES.find(c => c.aliases.some(a => a.toLowerCase().replace(/[^a-z0-9]+/g, '-') === normalized));
}

export function getCityById(id: string): City | undefined {
  return CITIES.find(c => c.id === id);
}

export function searchCities(query: string): City[] {
  if (!query || query.trim() === "") return [];
  const q = query.trim().toLowerCase();
  return CITIES.filter(c => 
    c.name.toLowerCase().includes(q) ||
    c.country.toLowerCase().includes(q) ||
    c.timezone.toLowerCase().includes(q) ||
    c.aliases.some(a => a.toLowerCase().includes(q))
  );
}

export function getCitiesByCountry(countryCode: string): City[] {
  return CITIES.filter(c => c.countryCode.toUpperCase() === countryCode.toUpperCase());
}

export function getCitiesByTimezone(timezone: string): City[] {
  return CITIES.filter(c => c.timezone === timezone);
}

export const POPULAR_CITIES = CITIES;

